POST localhost:8080/api/users
Accept: application/json

{
  "login": "jane_doe",
  "password": "4321"
}

###

POST localhost:8080/api/tokens
Accept: application/json

{
  "login": "matt",
  "password": "4123"
}

###

POST localhost:8080/api/users
Accept: application/json

{
  "login": "matt",
  "password": "4123"
}

###
POST localhost:8080/api/accounts
Authorization: ahahah