POST localhost:8080/users
Accept: application/json

{
  "login": "jane_doe",
  "password": "4321"
}

###

POST localhost:8080/token
Accept: application/json

{
  "login": "matt",
  "password": "4123"
}

###

POST localhost:8080/users
Accept: application/json

{
  "login": "matt",
  "password": "4123"
}