POST localhost:8080/api/users
Accept: application/json

{
  "login": "jane_doe",
  "password": "4321"
}

###

POST localhost:8080/api/tokens
Accept: application/json

{
  "login": "matt",
  "password": "4123"
}

###

POST localhost:8080/api/users
Accept: application/json

{
  "login": "matt",
  "password": "4123"
}

###
POST localhost:8080/api/accounts
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDI0NjU5NjAsIklEIjoiMDE4YzYyYTMtNjhkMy03OGExLWE1MDItNDk2ZGFkYmM3OGMzIn0.wGd7TL7u_M9FdB47-PbCn_mgZ0shTMGIbzK8V4-E6Ew
Accept: application/json

{
  "name": "first"
}